/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * e.g. 2014-06-29
 */
export type Iso8601 = string;
/**
 * Specify multiple accomplishments
 */
export type Highlights = string[];

/**
 * Your CV in YAML format
 */
export interface CV {
  /**
   * eg. image.jpg
   */
  image: string;
  /**
   * eg. Gilad Kutiel
   */
  name: string;
  /**
   * eg. Full Stack Developer
   */
  title: string;
  /**
   * eg. I'm a full stack developer with 10 years of experience
   */
  summary: string;
  contact: {
    /**
     * eg. example@gmail.com
     */
    email: string;
    /**
     * eg. +972-50-1234567
     */
    phone: string;
    /**
     * eg. https://www.linkedin.com/in/kutiel
     */
    linkedin: string;
    /**
     * eg. https://gilad.kutiel.com
     */
    website?: string;
    /**
     * eg. https://dblp.org/pid/1234567
     */
    dblp?: string;
    [k: string]: unknown;
  };
  work: {
    startDate: Iso8601;
    endDate: Iso8601;
    /**
     * e.g. Facebook
     */
    employer: string;
    /**
     * e.g. Software Engineer
     */
    position: string;
    /**
     * e.g. Social Media Company
     */
    summary: string;
    highlights?: Highlights;
  }[];
  education: {
    startDate: Iso8601;
    endDate: Iso8601;
    /**
     * e.g. Bachelor
     */
    degree: string;
    /**
     * e.g. Computer Science
     */
    field: string;
    /**
     * e.g. University of Cambridge
     */
    institute: string;
    /**
     * e.g. 92.1
     */
    gpa: number;
    /**
     * e.g. Thesis: 'The Evolution of Social Media'
     */
    summary: string;
    highlights?: Highlights;
  }[];
  publications?: {
    /**
     * e.g. 2014
     */
    year: number;
    /**
     * e.g. 'The Evolution of Social Media'
     */
    title: string;
    /**
     * e.g. Journal of Social Media
     */
    publisher: string;
    /**
     * e.g. Published in the Journal of Social Media
     */
    summary: string;
  }[];
  projects?: {
    /**
     * e.g. socily
     */
    name: string;
    /**
     * e.g. A social media platform for sharing photos
     */
    description: string;
    /**
     * e.g. https://myproject.com
     */
    url: string;
  }[];
  skills?: {
    /**
     * e.g. Python
     */
    name: string;
    /**
     * e.g. 10 years of experience
     */
    description: string;
  }[];
}
